/* Dependency-free browser QA: Node 22+ and locally installed Chrome or Edge. */
'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process'),{pathToFileURL}=require('node:url'),assert=require('node:assert/strict');
const browser=process.env.CHROME_PATH||['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p=>fs.existsSync(p));
if(!browser)throw Error('Set CHROME_PATH to a Chrome or Edge executable.');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'electric-potential-qa-'));
let connection;
const child=spawn(browser,['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--disable-background-networking','--remote-debugging-port=0','--user-data-dir='+temp,'about:blank'],{windowsHide:true,stdio:['ignore','ignore','pipe']});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
    let stderr='';child.stderr.on('data',d=>stderr+=d);
    for(let i=0;i<100&&!/DevTools listening on (ws:\/\/[^\s]+)/.test(stderr);i++)await delay(100);
    const address=stderr.match(/DevTools listening on (ws:\/\/[^\s]+)/)?.[1];if(!address)throw Error('Browser did not start: '+stderr);
    const ws=new WebSocket(address);connection=ws;await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});
    let next=0;const pending=new Map(),errors=[];
    ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.id){const p=pending.get(m.id);pending.delete(m.id);if(m.error)p.reject(Error(JSON.stringify(m.error)));else p.resolve(m.result);}};
    function cmd(method,params={},sessionId){return new Promise((resolve,reject)=>{const id=++next;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{} )}));});}
    const {targetId}=await cmd('Target.createTarget',{url:'about:blank'});
    const {sessionId}=await cmd('Target.attachToTarget',{targetId,flatten:true});
    const send=(method,params={})=>cmd(method,params,sessionId);
    await send('Runtime.enable');await send('Page.enable');
    const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
    await send('Emulation.setDeviceMetricsOverride',{width:1180,height:820,deviceScaleFactor:1,mobile:false});
    await send('Page.navigate',{url:pathToFileURL(path.join(__dirname,'index.html')).href});
    for(let i=0;i<100;i++){if(await evaluate('Boolean(window.simulation && simulation.grid.length)'))break;await delay(100);}
    assert.equal(await evaluate('Boolean(window.simulation)'),true);
    const settle=()=>evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r(true))))');
    const result={sizes:[],checks:[],screenshots:[]};
    for(const [width,height] of [[1024,768],[1180,820],[1366,768],[1280,800],[768,1024],[390,844]]) {
        await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});
        await evaluate(`simulation.togglePanel(${width>height});`);await settle();
        const dimensions=await evaluate(`(()=>{const c=document.getElementById('potentialCanvas').getBoundingClientRect(),p=document.querySelector('.ep-playbar').getBoundingClientRect();return {width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollWidth,canvas:{width:c.width,height:c.height},playbarBottom:p.bottom,bodyHeight:document.documentElement.scrollHeight};})()`);
        assert.ok(dimensions.scroll<=width+1,JSON.stringify(dimensions));assert.ok(dimensions.playbarBottom<=height+1,JSON.stringify(dimensions));assert.ok(dimensions.canvas.height>=100,JSON.stringify(dimensions));result.sizes.push(dimensions);
    }
    await send('Emulation.setDeviceMetricsOverride',{width:1180,height:820,deviceScaleFactor:2,mobile:false});await evaluate('simulation.togglePanel(true);simulation.defaults();');await settle();
    assert.equal(await evaluate('document.getElementById("probeV").textContent'),'8.99 V');
    assert.equal(await evaluate('document.getElementById("conclusion").hidden'),true);
    await evaluate('document.getElementById("revealBtn").click()');assert.equal(await evaluate('document.getElementById("conclusion").hidden'),false);
    const capture=async name=>{await settle();const {data}=await send('Page.captureScreenshot',{format:'png'});const file=path.join(temp,name+'.png');fs.writeFileSync(file,Buffer.from(data,'base64'));result.screenshots.push(file);};
    await capture('terrain-1180');
    await evaluate('document.getElementById("fieldToggle").click();document.getElementById("mapBtn").click();');await settle();assert.ok(await evaluate('simulation.lines.length>0'));
    await capture('map-1180');
    await evaluate('document.getElementById("saveABtn").click(); const q=document.getElementById("chargeValue");q.value=2;q.dispatchEvent(new Event("change"));');await settle();
    assert.equal(await evaluate('simulation.sources[0].value'),2);
    await evaluate('document.getElementById("compareBtn").click()');await settle();assert.equal(await evaluate('simulation.sources[0].value'),1);
    await evaluate('document.getElementById("compareBtn").click()');await settle();assert.equal(await evaluate('simulation.sources[0].value'),2);result.checks.push('A/B stores independent source configurations');
    await evaluate('document.getElementById("playBtn").click()');await delay(350);await evaluate('document.getElementById("playBtn").click()');await settle();
    const t=await evaluate('simulation.time');assert.ok(t>0);await delay(150);assert.equal(await evaluate('simulation.time'),t);
    await evaluate('document.getElementById("speed").value="0.25";document.getElementById("speed").dispatchEvent(new Event("change"));document.getElementById("contourToggle").click();');await settle();assert.equal(await evaluate('simulation.time'),t);
    await evaluate('document.getElementById("stepBtn").click()');await settle();assert.ok(Math.abs(await evaluate('simulation.time')-t-.1)<1e-8);
    await evaluate('document.getElementById("replayBtn").click()');await settle();assert.equal(await evaluate('simulation.time'),0);assert.equal(await evaluate('simulation.sources[0].value'),2);
    for(let i=0;i<4;i++)await evaluate('document.getElementById("playBtn").click();document.getElementById("playBtn").click();');await settle();assert.equal(await evaluate('simulation.running'),false);result.checks.push('pause, speed, toggles, replay, single step, repeated playback');
    await evaluate('simulation.setPreset("capacitor");document.getElementById("fieldToggle").checked=true;simulation.invalidate(true);');await settle();
    assert.equal(await evaluate('document.getElementById("probeE").textContent'),'11.29 N/C');await capture('capacitor-1180');
    await evaluate('document.querySelector("[data-add=point]").click();');await settle();assert.equal(await evaluate('simulation.sources.length'),3);
    await evaluate('document.getElementById("editTool").value="select";');
    const marker=await evaluate('(()=>{const s=simulation.sources.find(s=>s.id===simulation.selected),p=simulation.sourceScreen(s),r=simulation.canvas.getBoundingClientRect();return {x:r.left+p.x,y:r.top+p.y}})()');
    await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:marker.x,y:marker.y,id:1}]});
    await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:marker.x+45,y:marker.y-25,id:1}]});
    await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle();assert.ok(await evaluate('simulation.sources.at(-1).x>0'));assert.equal(await evaluate('simulation.drag'),null);result.checks.push('single-finger touch drag and pointer release');
    await evaluate('document.getElementById("clearBtn").click()');await settle();assert.equal(await evaluate('simulation.sources.length'),0);assert.equal(await evaluate('document.getElementById("probeV").textContent'),'0 V');
    await evaluate('simulation.defaults();document.querySelector("[data-add=sheet]").click();let tiltInput=document.getElementById("sheetTilt");tiltInput.value=90;tiltInput.dispatchEvent(new Event("change"));');await settle();assert.ok(await evaluate('document.getElementById("fieldNote").textContent.includes("切面內分量")'));
    await evaluate('document.getElementById("defaultsBtn").click()');await settle();assert.equal(await evaluate('simulation.sources.length'),1);assert.equal(await evaluate('simulation.sources[0].value'),1);assert.equal(await evaluate('document.getElementById("fieldToggle").checked'),false);
    await evaluate('document.getElementById("modeBtn").click()');await settle();assert.equal(await evaluate('getComputedStyle(document.querySelector(".ep-explanation")).display'), 'block');
    await evaluate('document.getElementById("modeBtn").click();document.getElementById("largeBtn").click();simulation.togglePanel(false)');await settle();await capture('large-text');
    await evaluate('simulation.defaults();simulation.setView("map");document.getElementById("fieldToggle").click()');await settle();
    assert.equal(await evaluate('simulation.lines.length'),16);
    await evaluate('document.getElementById("surfaceToggle").click();document.getElementById("sourceToggle").click()');await settle();
    assert.equal(await evaluate('document.getElementById("surfaceToggle").checked'),false);
    await evaluate('simulation.defaults();simulation.sources[0].value=-1;simulation.selected=simulation.sources[0].id;simulation.renderEditor();simulation.invalidate(true)');await settle();
    assert.equal(await evaluate('document.getElementById("probeV").textContent'),'-8.99 V');await capture('negative-terrain');
    await evaluate('simulation.setPreset("capacitor");simulation.setView("terrain");document.getElementById("contourToggle").checked=true;simulation.invalidate()');await settle();await capture('capacitor-terrain');
    await evaluate('simulation.sources[0].tilt=35;simulation.sources[0].angle=40;simulation.slice=1;simulation.invalidate(true)');await settle();await capture('tilted-sheet');
    await evaluate('simulation.defaults();document.getElementById("largeBtn").click();simulation.togglePanel(true)');
    await send('Emulation.setDeviceMetricsOverride',{width:1024,height:768,deviceScaleFactor:1,mobile:false});await settle();
    const largeLayout=await evaluate('({canvas:simulation.heightPx,bottom:document.querySelector(".ep-playbar").getBoundingClientRect().bottom,width:document.documentElement.scrollWidth})');
    assert.ok(largeLayout.canvas>=100 && largeLayout.bottom<=769 && largeLayout.width<=1024,JSON.stringify(largeLayout));result.largeLayout=largeLayout;await capture('large-1024');
    await evaluate('document.getElementById("playBtn").click();Object.defineProperty(document,"hidden",{configurable:true,value:true});document.dispatchEvent(new Event("visibilitychange"));delete document.hidden;');await settle();assert.equal(await evaluate('simulation.running'),false);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await evaluate('simulation.defaults();simulation.togglePanel(false)');await settle();await capture('portrait-390');
    result.checks.push('16 symmetric point-charge field lines; independent layers; negative terrain; tilted sheets; 1024 large text; background pause');
    result.checks.push('empty scene, arbitrary sheet tilt, defaults, explanation mode, large text, DPR=2');
    assert.deepEqual(errors,[]);result.consoleErrors=errors;console.log(JSON.stringify(result,null,2));
    await cmd('Browser.close');ws.close();
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{if(connection)connection.close();child.kill();});
